server:
  port: 9999

distancia:
  service:
    url: http://localhost:8082

monolito:
  url: http://localhost:8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
      - RewriteLocationResponseHeader
      routes:
      - id: pagamentos
        uri: http://localhost:8081
        predicates:
        - name: Path
          args:
            patterns:
            - /pagamentos/**
      - id: distancia
        uri: http://localhost:8082
        predicates:
        - Path=/distancia/**
        filters:
        - StripPrefix=1
      - id: monolito
        uri: http://localhost:8080
        predicates:
        - Path=/**
